#!/usr/bin/python

import sys
import time
from msdd_connection import *

c=Connection((sys.argv[1],23))

try:
    c.sendStringCommand('brd reset', expect_output=False)
    time.sleep(1)
except:
    pass
